name: Demo-for-actions

on: push
jobs:
   checkout-the-code:
    runs-on: ubuntu-20.04
    steps:
       - name: checkout-repo
         run: actions/checkout@V4
       - name: print the index.html
         run: cat index.html
