name: action for demo
on: push
jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - name: checkout index.html
        uses: actions/checkout@v4
      - name: print index.html
        run: cat index.html
  
