#workflow name
name: GIThub action name
#trigger
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: chckout the code
        uses: actions/checkout@v4
      - name: print index.html
        run: cat index.html

  
  
