#workflow name
name: Hello world
#trigger
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "A demo build"
  test:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Test phase
       run: echo "Running test case"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the app
        run: echo "Deploying the app"
  
  
