name: Demo-for-actions

on: push
jobs:
   checkout-the-code:
    runs-on: ubuntu-24.04
    steps:
       - name: checkout-repo
         uses: actions/checkout@v4
       - name: print the index.html
         run: cat index.html


